language: node_js

sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - graphviz

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH

node_js:
  - "7"
  - "8"

cache:
  yarn: true
  directories:
    - "node_modules"

script: yarn run dist

notifications:
  email:
    - aj@blockcollider.org
    - ak@blockcollider.org
    - pm@blockcollider.org
    - tk@blockcollider.org
