language: node_js

os:
  - linux
#  - osx

addons:
  apt:
    packages:
    - libzmq-dev

node_js:
  - "7"
  - "8"

cache:
  yarn: true
  directories:
    - "node_modules"

sudo: required
before_install:
  # Repo for Yarn
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

script: yarn run dist

notifications:
  email:
    - aj@blockcollider.org
    - ak@blockcollider.org
    - pm@blockcollider.org
    - tk@blockcollider.org
