language: node_js

os:
  - linux
  - osx
  
node_js:
  - "7"
  - "8"

cache:
  directories:
    - "node_modules"

notifications:
  email:
    - aj@blockcollider.org
    - ak@blockcollider.org
    - pm@blockcollider.org
    - tk@blockcollider.org
